test:test.cc
	g++ test.cc -o test -lpthread -lfmt -lspdlog -lboost_system -ljsoncpp -L/home/epsda/RPC_Framework_JSON/rpc_framework/utils/ -I/home/epsda/RPC_Framework_JSON

.PHONY:clean
clean:
	rm -f test